### ISSUE TITLE
Setup the frontend of the project

### ISSUE THREAD

**Issue by 6im0n** [Marius-P1/Survivor-Pool#9]
**Is your feature request related to a problem? Please describe.**
We need to setup the project frontend that will help us be more efficient with the website development.

**Describe the solution you'd like**
The frontend will based on [Vue](https://vuejs.org/) + [typescript](https://www.typescriptlang.org/) and the following technologies
- NodeJS
- PrimeVue (For UI components)
- Eslint (a static code analysis tool for identifying )

**Comment by Mounik-tech** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
